# -*- coding: utf-8 -*-
"""restful.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svQhy9MlWchHfooMLOIoudScIyI8jjd8
"""

import requests
import json
import argparse

class RestfulClient:
    BASE_URL = "https://jsonplaceholder.typicode.com"

    def __init__(self, method, endpoint, outfile=None):
        self.method = method
        self.endpoint = endpoint
        self.outfile = outfile

    def perform_request(self):
        url = f"{self.BASE_URL}{self.endpoint}"
        response = None

        if self.method == 'get':
            response = requests.get(url)
        elif self.method == 'post':
            print(" no POST method for this.")
            return
        else:
            print(f"Invalid method: {self.method}")
            return

        self.handle_response(response)

    def handle_response(self, response):
        print(f"HTTP Status Code: {response.status_code}")

        if response.status_code // 100 == 2:
            if self.outfile:
                self.save_to_file(response.json())
            else:
                print(json.dumps(response.json(), indent=2))
        else:
            print(f"Error: {response.status_code}")

    def save_to_file(self, data):
        if self.outfile.endswith('.json'):
            with open(self.outfile, 'w') as json_file:
                json.dump(data, json_file, indent=2)
            print(f"Response saved to {self.outfile}")
        else:
            print("Unsupported output file format. Supported formats: .json")

def run_restful_client(method, endpoint, outfile=None):
    client = RestfulClient(method, endpoint, outfile)
    client.perform_request()

# Example of usage:
run_restful_client('get', '/posts/1', outfile='output.json')